# https://travis-ci.org/tornadoweb/tornado
language: python
python:
    - 3.5
    - 3.6

install:
    - pip install pylint
    - pip install pyyaml


script:
    - pylint dz1/task_class.py

sudo: false

matrix:
    fast_finish: true