# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='date',
            field=models.DateTimeField(verbose_name='впишите дату сюда'),
        ),
        migrations.AlterField(
            model_name='creation',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название задачи'),
        ),
    ]
