# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='points',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='Зачислено очков:'),
        ),
    ]
